# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='rating',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rating',
            name='supply',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rating',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
    ]
