# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20170528_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name_coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_name', to='scraper.Coins'),
        ),
    ]
